name: Test

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/test.yml"
      - "packages/**"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "packages/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.30
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run tests
        run: bun run --filter '*' test
